### ISSUE TITLE
Limitation: for Mellanox drivers - need to disable ipoib enhanced mode

### ISSUE THREAD

**Issue by adrianchiris** [Mellanox/ipoib-cni#9]
It seems that loopback traffic is dropped when this feature is enabled.
pod2pod traffic will fail on the same host

To disable:
In Upstream kernel : compile with CONFIG_MLX5_CORE_IPOIB=n
In Mellanox OFED: define ipoib_enhanced=0 mod param when loading ib_ipoib  (add “options ib_ipoib ipoib_enhanced=0” to etc/modprobe.d/ib_ipoib.conf)

**Comment by adrianchiris** [comment]
Implication of disbling IPoIB Enchanced mode for Mellanox driver:

1. larger memory consumption by kernel (QP created pair ipoib child)
2. lower traffic bandwidth on IPoIB interfaces (compared to when enhanced mode is enabled)

**Comment by moshe010** [comment]
should work from OFED 5.1 or newer and kernel 5.8 or newer
